### ISSUE TITLE
[BUG] not reporting when failed index

### ISSUE THREAD

**Issue by RodrigoDornelles** [opensearch-project/opensearch-go#525] opened 2024-04-12 14:28 UTC
### How can one reproduce the bug?
There is no error log when there is a wrong configuration, such as failed SSL, wrong DNS, permission error...

#### correct config logs

```
2024-04-08T14:00:03Z D! [outputs.opensearch] indexName- github_push-audit-2024_04_08
2024-04-08T14:00:03Z D! [outputs.opensearch] Indexed to OpenSearch with status- [201] Result- created DocumentID- c61b1e60c648cc1fc86222e059d36d89c3eee5db49d4d36b16a96d0fbbcc22b9 
2024-04-08T14:00:03Z D! [outputs.opensearch] Successfully indexed [1] documents
2024-04-08T14:00:03Z D! [outputs.opensearch] Wrote batch of 346 metrics in 73.075738ms
2024-04-08T14:00:03Z D! [outputs.opensearch] Buffer fullness: 0 / 10000 metrics
```

#### wrong config logs

```
2024-04-08T14:00:03Z D! [outputs.opensearch] indexName- github_push-audit-2024_04_08
2024-04-08T14:00:03Z D! [outputs.opensearch] Successfully indexed [1] documents
2024-04-08T14:00:03Z D! [outputs.opensearch] Wrote batch of 346 metrics in 73.075738ms
2024-04-08T14:00:03Z D! [outputs.opensearch] Buffer fullness: 0 / 10000 metrics
```

 * Note that there is no failure signal such as an error message.
 * is also missing by this metric:<br/>`2024-04-08T14:00:03Z D! [outputs.opensearch] Indexed to OpenSearch with status- [201] Result- created DocumentID- c61b1e60c648cc1fc86222e059d36d89c3eee5db49d4d36b16a96d0fbbcc22b9 `

#### expected with wrong  config logs

```
2024-04-08T14:00:03Z D! [outputs.opensearch] indexName- github_push-audit-2024_04_08
2024-04-08T14:00:03Z D! [outputs.opensearch] some error message about failed
2024-04-08T14:00:03Z D! [outputs.opensearch] Failed trying indexing [1] documents
```

### What is your host/environment?
Linux 5.15, Docker 26.0, Telegraf 1.30.1

### Do you have any additional context?

issue related https://github.com/influxdata/telegraf/issues/15119 https://github.com/influxdata/telegraf/issues/14334

**Comment by Jakob3xD** [comment] 2024-04-15 08:24
@RodrigoDornelles can you please give us more information and some clear instructions on how to reproduce this. Especially for ppl. who don't use telegraf.
Moreover the http bulk response would be interesting.

As a note to us: telegraf uses v2 of opensearch-go

**Comment by RodrigoDornelles** [comment] 2024-04-15 11:26
As you can see in issue https://github.com/influxdata/telegraf/issues/15119, using any configuration with valid syntax, but incorrect parameters such as password or host will reproduce the error.

who said there was a possibility that the problem could be in this plugin was @powersj with his comment https://github.com/influxdata/telegraf/issues/15119#issuecomment-2051713377

**Comment by dblock** [comment] 2024-04-15 11:42
So this problem only happens with telegraf? If so sounds like an issue with that agent rather than a problem with the library itself. Any objections we close this here @RodrigoDornelles, or do you have reasons to believe the client is the issue?

**Comment by RodrigoDornelles** [comment] 2024-04-15 11:58
I haven't tested it elsewhere, well if there is a feature that reports errors in the plugin, the error is certainly not here.

**Closed** 2024-04-15 16:42 UTC
Labels: bug, question

**Comment by dblock** [comment] 2024-04-15 16:43
Looks like this was root caused in https://github.com/influxdata/telegraf/issues/15119#issuecomment-2057093872.
