### ISSUE TITLE
[FEATURE] Support Point In Time API

### ISSUE THREAD

**Issue by Omkar-Waingankar** [opensearch-project/opensearch-go#305] opened 2023-04-17 20:38 UTC
### Is your feature request related to a problem?
Currently, the OpenSearch API exposes endpoints to create, manage, and delete PITs (see: https://opensearch.org/docs/2.4/opensearch/point-in-time-api/). Unfortunately, the Go SDK does not provide support for these API endpoints.

### What solution would you like?
I would like to see a proposal and implementation of a `type PointInTime` (and `PointInTimeCreateRequest`, `PointInTimeDeleteRequest`, etc.), along with a number of associated functions, to manage PITs as specified in the OpenSearch docs above.

### What alternatives have you considered?
Right now, our team simply makes API calls to our OpenSearch cluster to create and manage PITs. Ideally, we would be using the Go SDK for all operations with OpenSearch. To keep PITs alive longer, we are able to use the existing SearchRequest functionality.

### Do you have any additional context?
If this feature is not in scope, I would be happy to make a PR for it as it will directly benefit my company's operations.

**Comment by VachaShah** [comment] 2023-04-18 01:22
Thank you for raising this feature request. We would gladly accept a PR for this feature!

**Comment by Omkar-Waingankar** [comment] 2023-04-19 01:41
# PIT Proposal

@VachaShah great! Here’s a rough proposal for how I would implement functionality to support the various PIT endpoints. Happy to hear any and all feedback, and after that I'll begin implementation.

## Notes

- I have purposely omitted functions such as WithPretty, WithHuman, WithErrorTrace, WithFilterPath, and WithHeader because I am unsure if they are actually needed in order for my PR to be accepted.

## Create A PIT

```go
type PointInTimeCreate func(index []string, keepAlive time.Duration, o ...func(*PointInTimeCreateRequest)) (*Response, error)

func (f PointInTimeCreate) WithPreference(v string) func(*PointInTimeCreateRequest)
func (f PointInTimeCreate) WithRouting(v string) func(*PointInTimeCreateRequest)
func (f PointInTimeCreate) WithExpandWildcards(v []string) func(*PointInTimeCreateRequest)
func (f PointInTimeCreate) WithAllowPartialPITCreation(v bool) func(*PointInTimeCreateRequest)
```

```go
type PointInTimeCreateRequest struct {
	Index []string //required

	KeepAlive time.Duration. //required

	Preference string
	Routing string
	ExpandWildcards []string
	AllowPartialPITCreation *bool
}

func (r PointInTimeCreateRequest) Do(ctx context.Context, transport Transport) (*Response, error)
```

## Extend A PIT

No additional work is necessary to support this endpoint because the PIT-related information can simply be passed to the `Body io.Reader` property of a SearchRequest.

## List All PITs

```go
type PointInTimeList func(o ...func(*PointInTimeListRequest)) (*Response, error)
```

```go
type PointInTimeListRequest struct {}

func (r PointInTimeListRequest) Do(ctx context.Context, transport Transport) (*Response, error)
```

## Delete A PIT

Note: Default is delete all PIT

```go
type PointInTimeDelete func(o ...func(*PointInTimeListRequest)) (*Response, error)

func (f PointInTimeDelete) WithPITID(v []string) func(*PointInTimeDeleteRequest)
```

```go
type PointInTimeDeleteRequest struct {
	PITID []string
}

func (r PointInTimeDeleteRequest) Do(ctx context.Context, transport Transport) (*Response, error)
```

## PIT Segments

Note: Default is return segments for all PIT

```go
type PointInTimeSegments func(o ...func(*PointInTimeSegmentsRequest)) (*Response, error)

func (f PointInTimeSegments) WithPITID(v []string) func(*PointInTimeSegmentsRequest)
```

```go
type PointInTimeSegmentsRequest struct {
	PITID []string
}

func (r PointInTimeSegmentsRequest) Do(ctx context.Context, transport Transport) (*Response, error)
```

**Comment by Jakob3xD** [comment] 2023-04-27 08:09
There is already an implementation for PIT which is not yet released but already merged. Moreover the issue is duplicate to #251.
https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/api.pointintime.create.go
https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/api.pointintime.delete.go
https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/api.pointintime.get.go

Feel free to look through it and open an PR if we are missing things.

**Comment by dblock** [comment] 2023-04-27 16:04
Let's close!

**Closed by dblock** 2023-04-27 16:04 UTC
Labels: enhancement
