### ISSUE TITLE
[BUG] ExplainRequest does not work properly 

### ISSUE THREAD

**Issue by zethuman** [opensearch-project/opensearch-go#281] opened 2023-04-05 16:16 UTC
### What is the bug?
ExplainRequest return error with empty structure without details. 

### How can one reproduce the bug?
Now, I am writing test cases to the document APIs #280 and found this problem. However I can not identify it.

To reproduce bug, create index, create document with id "2" and request Explain API
```
r: opensearchapi.ExplainRequest{
  Index:      index,
  DocumentID: "2",
  Body:       strings.NewReader(`{ "query": { "match": {"year": "2019" } } }`),
  Human:      true,
  ErrorTrace: true,
},
```
I got this:

```
Do() error = error: {[]    }, status: 0, wantErr false
    --- FAIL: TestUpdateRequest_Do/TestExplainRequest_Do (0.00s)
```

### What is the expected behavior?
At least details of error, even better successfully found document

### What is your host/environment?
MacOS Ventura 

### Do you have any screenshots?
<img width="814" alt="image" src="https://user-images.githubusercontent.com/51375666/230141673-a8c1ea19-5858-44e8-b6ab-0f6e4538004d.png">

**Comment by Jakob3xD** [comment] 2023-04-07 02:03
The empty error body is caused by a 404 without a error body. The request returns following instead of an expected error response:
```
{"_index":"index-2023-04-07-03-57-18","_id":"2","matched":false}
```

Need to check if this is wanted from opensearch and if so fix the error handling to return the non-parsed error.

**Comment by Jakob3xD** [comment] 2023-04-12 16:36
The incorrect error response is fixed but the test added by #285 is not working correctly.
lt. comment the explain api returns 200 without a body.
https://github.com/opensearch-project/opensearch-go/pull/285#discussion_r1162928808

**Comment by zethuman** [comment] 2023-04-14 01:08
Yes, it turns out I didn’t report it, I even tried to update the indexes before calling, it doesn’t help

**Comment by Jakob3xD** [comment] 2023-11-20 12:09
Should no longer be relevant with https://github.com/opensearch-project/opensearch-go/pull/421 merged. Please reopen if the issue sill persists.

**Closed by Jakob3xD** 2023-11-20 12:09 UTC
Labels: bug
